# Build container with single module file per specific version
FROM alpine:3.18
ARG KERNEL_VERSION

COPY ko/pf-ring-${KERNEL_VERSION}.ko /opt/modules/pf-ring-${KERNEL_VERSION}.ko
COPY scripts/entrypoint.sh /opt/scripts/entrypoint.sh
RUN apk add kmod

ENTRYPOINT [ "/opt/scripts/entrypoint.sh" ]