# Build container with all available modules
FROM alpine:3.18

COPY ko/*.ko /opt/modules/
COPY scripts/entrypoint.sh /opt/scripts/entrypoint.sh

RUN apk add kmod
ENTRYPOINT [ "/opt/scripts/entrypoint.sh" ]