name: Build and Push PF_RING builder docker images

on:
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      builders: ${{ steps.set-matrix.outputs.builders }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare list of builders
        id: set-matrix
        run: |
          echo "Listing builders..."
          builders=$(ls -d builders/* | jq -R -s -c 'split("\n")[:-1]')
          echo "builders=${builders}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        builder: ${{ fromJson(needs.prepare-matrix.outputs.builders) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./builders/${{ matrix.builder }}
          file: ./builders/${{ matrix.builder }}/Dockerfile
          push: true
          tags: kubeshark/pf-ring-builder:${{ matrix.builder }}