name: Build and Push PF_RING modules

on:
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-matrix.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare list of versions
        id: set-matrix
        run: |
          echo "Listing kernel modules..."
          versions=();
          for f in $(ls modules/*.ko); do
            version=$(echo $f | sed -E 's/.*pf-ring-(.*)\.ko/\1/');
            versions+=("$version")
          done

          versions_json=$(echo "${versions[@]}" | tr -d '\n' | jq -R -s -c 'split(" ")')
          echo "versions=${versions_json}" >> $GITHUB_OUTPUT

  build-and-push-container:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.prepare-matrix.outputs.versions) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./modules
          file: ./modules/Dockerfile
          push: true
          tags: kubeshark/pf-ring-module:${{ matrix.version }}
          build-args: |
            KERNEL_VERSION=${{ matrix.version }}

  upload-modules-to-s3:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1-node16
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      #     role-session-name: buildsession
      #     aws-region: us-east-2

      - name: Copy kernel modules
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          for f in $(ls modules/*.ko); do
            version=$(echo $f | sed -E 's/.*pf-ring-(.*)\.ko/\1/');
            aws s3 cp $f ${{ secrets.AWS_PF_RING_BUCKET }}/${version}/pf_ring.ko
          done

          echo "Copy versions metadata"
          echo ${{ needs.prepare-matrix.outputs.versions }} > versions.json
          aws s3 cp versions.json ${{ secrets.AWS_PF_RING_BUCKET }}/versions.json
