name: Build and Push PF_RING module docker images

on:
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-matrix.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare list of versions
        id: set-matrix
        run: |
          echo "Listing kernel modules..."
          versions=();
          for f in $(ls modules/*.ko); do
            version=$(echo $f | sed -E 's/.*pf-ring-(.*)\.ko/\1/');
            versions+=("$version")
          done

          versions_json=$(echo "${versions[@]}" | tr -d '\n' | jq -R -s -c 'split(" ")')
          echo "versions=${versions_json}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.prepare-matrix.outputs.versions) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./modules
          file: ./modules/Dockerfile
          push: true
          tags: kubeshark/pf-ring-module:${{ matrix.version }}
          build-args: |
            KERNEL_VERSION=${{ matrix.version }}