name: Go Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Lint Go code
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
        args: --timeout=5m

    - name: Run Go tests
      run: go test ./...

    - name: Build
      run: go build ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}